import {Link} from 'react-router-dom';import {motion} from 'framer-motion';import {ArrowRight,HeartHandshake,ShieldCheck,Activity,MessageCircle,Phone,Quote,Star} from 'lucide-react';import {Swiper,SwiperSlide} from 'swiper/react';import {Navigation} from 'swiper/modules';import {business} from '../config/business';import {services,team,facilities,articles} from '../data/content';import {generalWhatsApp} from '../utils/whatsapp';import AppointmentForm from '../components/AppointmentForm';
const Reveal=({children,className=''}:{children:React.ReactNode,className?:string})=><motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.65}}>{children}</motion.div>;
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><motion.span initial={{opacity:0}} animate={{opacity:1}} className="eyebrow">Cuidado veterinario integral · Quito</motion.span><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>Su bienestar.<br/><em>Nuestra vocación.</em></motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}}>Medicina clara, cercana y responsable para los animales que hacen de tu casa un hogar.</motion.p><motion.div className="hero-actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.4}}><Link className="button" to="/contact#appointment">Agendar una cita <ArrowRight/></Link><a className="text-link" href={generalWhatsApp}><MessageCircle/> Escribir por WhatsApp</a></motion.div></div><motion.div className="hero-image" initial={{opacity:0,scale:1.03}} animate={{opacity:1,scale:1}} transition={{duration:1}}><img src="https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1800&q=88" alt="Veterinaria examinando con cuidado a un perro"/><div className="hero-note"><span>Consulta con calma</span><b>Escuchamos. Evaluamos.<br/>Explicamos.</b></div></motion.div>{business.emergencyEnabled&&<div className="emergency-mini"><Activity/><div><small>¿Es una emergencia?</small><b>Habla con nuestro equipo ahora</b></div><a href={`tel:${business.emergencyPhone}`}>{business.emergencyPhone}</a></div>}</section>
<section className="trust">{[[HeartHandshake,'Trato respetuoso','Cuidado de bajo estrés'],[ShieldCheck,'Protocolos seguros','Decisiones responsables'],[Activity,'Medicina moderna','Tecnología con propósito']].map(([Icon,t,s],i)=><div key={t}><Icon/><span><b>{t}</b><small>{s}</small></span>{i<2&&<i/>}</div>)}</section>
<section className="section services"><Reveal><span className="eyebrow">Nuestros servicios</span><div className="section-title"><h2>Medicina que acompaña<br/><em>cada etapa de su vida.</em></h2><p>Desde una consulta preventiva hasta cuidados especializados, cada decisión se conversa contigo.</p></div></Reveal><div className="service-layout"><Link to={`/services/${services[0].slug}`} className="service-feature"><img src={services[0].img} alt="Consulta veterinaria integral"/><div><services.0.icon/><span>01 · Atención principal</span><h3>{services[0].title}</h3><p>{services[0].text}</p><b>Conocer el servicio <ArrowRight/></b></div></Link><div className="service-list">{services.slice(1).map((s,i)=><Link to={`/services/${s.slug}`} key={s.slug}><span>0{i+2}</span><s.icon/><div><h3>{s.title}</h3><p>{s.text}</p></div><ArrowRight/></Link>)}</div></div><Link className="under-link" to="/services">Ver todos los servicios <ArrowRight/></Link></section>
<section className="pet-split"><div className="pet-photo dog"><div><span className="eyebrow light-text">Cuidamos perros</span><h2>Prevención para una vida activa.</h2><Link to="/contact#appointment">Planificar su revisión <ArrowRight/></Link></div></div><div className="pet-photo cat"><div><span className="eyebrow light-text">Cuidamos gatos</span><h2>Consultas tranquilas, a su ritmo.</h2><Link to="/contact#appointment">Planificar su revisión <ArrowRight/></Link></div></div></section>
<section className="section philosophy"><Reveal className="philosophy-copy"><span className="eyebrow">Nuestra forma de cuidar</span><h2>No tratamos casos.<br/><em>Cuidamos vínculos.</em></h2><p>Una buena atención empieza por observar sin prisa y explicar sin tecnicismos. Diseñamos cada visita para que tú entiendas las opciones y tu mascota se sienta segura.</p><Link className="under-link" to="/team">Conoce al equipo <ArrowRight/></Link></Reveal><div className="philosophy-image"><img loading="lazy" src="https://images.unsplash.com/photo-1612531386530-97286d97c2d2?auto=format&fit=crop&w=1400&q=85" alt="Veterinaria acompañando a una familia y su perro"/><blockquote><Quote/><p>La medicina excelente también sabe escuchar.</p></blockquote></div></section>
<section className="section team"><span className="eyebrow">Profesionales cercanos</span><div className="section-title"><h2>Experiencia que inspira<br/><em>confianza.</em></h2><Link className="under-link" to="/team">Ver equipo <ArrowRight/></Link></div><Swiper modules={[Navigation]} navigation spaceBetween={24} slidesPerView={1.15} breakpoints={{700:{slidesPerView:2.15},1100:{slidesPerView:3}}}>{team.map(m=><SwiperSlide key={m.name}><div className="team-card"><img loading="lazy" src={m.img} alt={m.name}/><span>{m.role}</span><h3>{m.name}</h3><p>{m.exp}</p></div></SwiperSlide>)}</Swiper></section>
<section className="facilities-preview"><div className="section-title light-title"><div><span className="eyebrow light-text">Espacios que dan calma</span><h2>Diseñados para cuidar<br/>mejor.</h2></div><Link className="under-link" to="/facilities">Explorar la clínica <ArrowRight/></Link></div><div className="facility-grid">{facilities.map(([name,img],i)=><figure key={name} className={i===0?'large':''}><img loading="lazy" src={img} alt={name}/><figcaption>{name}<span>0{i+1}</span></figcaption></figure>)}</div></section>
<section className="section stories"><Reveal><span className="eyebrow">Historias reales</span><blockquote><div className="stars">{[1,2,3,4,5].map(x=><Star key={x}/>)}</div>“Nos explicaron cada paso con mucha paciencia. Luna estuvo tranquila y nosotros salimos sabiendo exactamente cómo cuidarla en casa.”<footer>María & Luna <small>· Consulta preventiva</small></footer></blockquote></Reveal></section>
<section className="section journal"><span className="eyebrow">Cuidados para compartir</span><div className="section-title"><h2>Notas para una vida<br/><em>más sana juntos.</em></h2><Link className="under-link" to="/pet-care">Ver todas las notas <ArrowRight/></Link></div><div className="article-grid">{articles.map(a=><article key={a.title}><img loading="lazy" src={a.img} alt=""/><span>{a.cat}</span><h3>{a.title}</h3><Link to="/pet-care">Leer nota <ArrowRight/></Link></article>)}</div></section>
<section id="appointment" className="appointment-wrap"><div className="appointment-intro"><span className="eyebrow light-text">Tu próxima visita</span><h2>Empecemos a cuidarles<br/><em>desde hoy.</em></h2><p>Completa la solicitud y nuestro equipo confirmará contigo por WhatsApp.</p><div><Phone/><span><small>¿Prefieres llamar?</small><b>{business.phone}</b></span></div></div><AppointmentForm/></section>
<section className="emergency"><Activity/><div><span className="eyebrow light-text">Atención urgente</span><h2>¿Tu mascota necesita ayuda inmediata?</h2><p>No esperes una respuesta por formulario. Llámanos para orientarte.</p></div><a className="button cream" href={`tel:${business.emergencyPhone}`}>Llamar ahora <Phone/></a></section>
</>}
